### ISSUE TITLE
ts.el is only available on melpa

### ISSUE THREAD

**Issue by mujo-hash** [rougier/nano-agenda#6]
As this package is available on elpa, I think it would be cleaner if it only depended on other elpa packages.

I'm not familiar enough with the emacs package ecosystem to recommend a replacement, and I only noticed this when installing nano-agenda from elpa without melpa configured.

Thank you for making the nano-* packages available, I think they are incredible.

**Comment by mujo-hash** [comment]
For completeness, here is the error message when installing from elpa:
`nano-agenda.el:45:1:Error: Cannot open load file: No such file or directory, ts`

**Comment by rougier** [comment]
There is actually an ongoing discussion for  having @alphapapa library to be added on elpa but I don't knwo what's the status. @alphapapa, do you have any update?

**Comment by rougier** [comment]
@mujo-hash I've removed the dependency.

**Comment by alphapapa** [comment]
Apologies for the delay.  I do intend to add `ts` to GNU ELPA, but I don't know how soon it will get done.
