### ISSUE TITLE
Show DEADLINE and SCHEDULED entries also

### ISSUE THREAD

**Issue by maikol-solis** [rougier/nano-agenda#7]
Hi! 

I followed your talk in the EmacsConf 2021 (https://emacsconf.org/2021/talks/design/), and I decided to try nano-agenda. 

However, I noticed that only the timestamped entries (à la `org-gcal`) are shown. The DEADLINE and SCHEDULED times are ignored. 

I think it would be a great addition if `nano-agenda` could show those entries also. 

Best.

**Comment by rougier** [comment]
Someone proposed some code to select what to be displayed but I cannot find the code right now. I need to finish reviewer GitHub notification and I'll try again to find the code. Don't hesitate to remind me.

**Comment by maikol-solis** [comment]
Sure don't worry.  Thanks again.

**Comment by rougier** [comment]
I found it, it was just in plain sight: https://github.com/rougier/nano-agenda/pull/5. I'm waiting for the copyright for to be signed before merge. If you can test the code, that would be great (or if you have any comment).

**Comment by edgar-vincent** [comment]
Should this be closed, since #5 has been merged?
